### PR TITLE
Add ES 3.1 support

### PR DESCRIPTION
**Pull request by davidrogers-unity**

### CODE REVIEW

**Comment by cpbotha** [comment]
Is there any more information about this work? Is this ES 3.1 support patch being used anywhere?

**Comment by aras-p** [comment]
I've somehow never merged this patch, but quite possibly ES3.1 might come as a byproduct if I do merge with upstream Mesa one of these days. But right now I don't have much time to do that...

**Comment by cpbotha** [comment]
Thanks very much for responding!

We've just cherry-picked the ES31 patch into current master, fixed a bunch of merge conflicts, and then merged in https://github.com/aras-p/glsl-optimizer/pull/91 to get it all to build cleanly on Linux.

Will report back here as soon as we've tested this on real ES31 shader code.

**Comment by aras-p** [comment]
Seems to be a really old PR, and I forgot why I have not merged it int yet (also, no tests to know if it works). And would conflict with current master branch. @davidrogers-unity please reopen if still relevant.

**Pull request closed without merging**
