### PR TITLE
Fix texelFetch & sampler2DMS support

### PR DESCRIPTION
**Pull request by zeux**
This requires bumping the GLSLVersion constant up but AFAICS it's not used for the output - #version directive is preserved, and it's just used to populate the available definitions/features. Let me know if you want me to fix this by making another kGlslTarget enum value.

More importantly, texelFetch was converted to textureProj during ir->glsl pass :) so this fixes that.

I'm not sure how to run tests so I haven't ran tests :(

### CODE REVIEW

**Comment by zeux** [comment]
Ah, I figured out how to run tests but tests don't seem to pass on current master due to some differences in Metal output (looks like there's an extra #pragma diagnostic added now, and test output wasn't regenerated).

**Comment by aras-p** [comment]
Yeah possibly the metal test output is not up to latest. That said, do you have some small test for MSAA fetch? (too lazy/busy to do one myself right now)

**Comment by zeux** [comment]
I'll add a test for MSAA fetch. I think my change also breaks textureProjLod (wasn't aware of its existence...) - not sure if there are tests for this, if not I'll add them as well.

**Comment by zeux** [comment]
Updated Metal test output, fixed textureProjLod (there was a test for it, yay!) and added a test for texelFetch with sampler2DMS.

**Comment by aras-p** [comment]
Awesome, thanks!

**Pull request merged**
